/* Auto-generated by genmsg_cpp for file /home/student/workspace/Simulator/msg/FormationMessage.msg */
#ifndef SIMULATOR_MESSAGE_FORMATIONMESSAGE_H
#define SIMULATOR_MESSAGE_FORMATIONMESSAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Simulator
{
template <class ContainerAllocator>
struct FormationMessage_ {
  typedef FormationMessage_<ContainerAllocator> Type;

  FormationMessage_()
  : radius(0.0)
  , heading(0.0)
  , seed_id(0)
  , formation_id(0)
  {
  }

  FormationMessage_(const ContainerAllocator& _alloc)
  : radius(0.0)
  , heading(0.0)
  , seed_id(0)
  , formation_id(0)
  {
  }

  typedef double _radius_type;
  double radius;

  typedef double _heading_type;
  double heading;

  typedef int32_t _seed_id_type;
  int32_t seed_id;

  typedef int32_t _formation_id_type;
  int32_t formation_id;


private:
  static const char* __s_getDataType_() { return "Simulator/FormationMessage"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "bd72cb9b2bb0c98007298d13c50d1bb0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 radius\n\
float64 heading\n\
#Vector  seed_frp\n\
int32   seed_id\n\
int32   formation_id\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, radius);
    ros::serialization::serialize(stream, heading);
    ros::serialization::serialize(stream, seed_id);
    ros::serialization::serialize(stream, formation_id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, radius);
    ros::serialization::deserialize(stream, heading);
    ros::serialization::deserialize(stream, seed_id);
    ros::serialization::deserialize(stream, formation_id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(radius);
    size += ros::serialization::serializationLength(heading);
    size += ros::serialization::serializationLength(seed_id);
    size += ros::serialization::serializationLength(formation_id);
    return size;
  }

  typedef boost::shared_ptr< ::Simulator::FormationMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Simulator::FormationMessage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FormationMessage
typedef  ::Simulator::FormationMessage_<std::allocator<void> > FormationMessage;

typedef boost::shared_ptr< ::Simulator::FormationMessage> FormationMessagePtr;
typedef boost::shared_ptr< ::Simulator::FormationMessage const> FormationMessageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Simulator::FormationMessage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Simulator::FormationMessage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Simulator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Simulator::FormationMessage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Simulator::FormationMessage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Simulator::FormationMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bd72cb9b2bb0c98007298d13c50d1bb0";
  }

  static const char* value(const  ::Simulator::FormationMessage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbd72cb9b2bb0c980ULL;
  static const uint64_t static_value2 = 0x07298d13c50d1bb0ULL;
};

template<class ContainerAllocator>
struct DataType< ::Simulator::FormationMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Simulator/FormationMessage";
  }

  static const char* value(const  ::Simulator::FormationMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Simulator::FormationMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 radius\n\
float64 heading\n\
#Vector  seed_frp\n\
int32   seed_id\n\
int32   formation_id\n\
";
  }

  static const char* value(const  ::Simulator::FormationMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Simulator::FormationMessage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Simulator::FormationMessage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.radius);
    stream.next(m.heading);
    stream.next(m.seed_id);
    stream.next(m.formation_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FormationMessage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Simulator::FormationMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Simulator::FormationMessage_<ContainerAllocator> & v) 
  {
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "seed_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.seed_id);
    s << indent << "formation_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.formation_id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_FORMATIONMESSAGE_H

