/* Auto-generated by genmsg_cpp for file /home/student/workspace/Simulator/msg/RelationshipMessage.msg */
#ifndef SIMULATOR_MESSAGE_RELATIONSHIPMESSAGE_H
#define SIMULATOR_MESSAGE_RELATIONSHIPMESSAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Simulator
{
template <class ContainerAllocator>
struct RelationshipMessage_ {
  typedef RelationshipMessage_<ContainerAllocator> Type;

  RelationshipMessage_()
  : id(0)
  {
  }

  RelationshipMessage_(const ContainerAllocator& _alloc)
  : id(0)
  {
  }

  typedef int32_t _id_type;
  int32_t id;


private:
  static const char* __s_getDataType_() { return "Simulator/RelationshipMessage"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c5e4a7d59c68f74eabcec876a00216aa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#VectorMessage desired\n\
#VectorMessage actual\n\
int32 id\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(id);
    return size;
  }

  typedef boost::shared_ptr< ::Simulator::RelationshipMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Simulator::RelationshipMessage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RelationshipMessage
typedef  ::Simulator::RelationshipMessage_<std::allocator<void> > RelationshipMessage;

typedef boost::shared_ptr< ::Simulator::RelationshipMessage> RelationshipMessagePtr;
typedef boost::shared_ptr< ::Simulator::RelationshipMessage const> RelationshipMessageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Simulator::RelationshipMessage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Simulator::RelationshipMessage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Simulator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Simulator::RelationshipMessage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Simulator::RelationshipMessage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Simulator::RelationshipMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const  ::Simulator::RelationshipMessage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::Simulator::RelationshipMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Simulator/RelationshipMessage";
  }

  static const char* value(const  ::Simulator::RelationshipMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Simulator::RelationshipMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#VectorMessage desired\n\
#VectorMessage actual\n\
int32 id\n\
";
  }

  static const char* value(const  ::Simulator::RelationshipMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Simulator::RelationshipMessage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Simulator::RelationshipMessage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RelationshipMessage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Simulator::RelationshipMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Simulator::RelationshipMessage_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_RELATIONSHIPMESSAGE_H

