"""autogenerated by genmsg_py from RelationshipMessage.msg. Do not edit."""
import roslib.message
import struct

import Simulator.msg

class RelationshipMessage(roslib.message.Message):
  _md5sum = "8dd66b6189dbb1e0ac86b46da7968d70"
  _type = "Simulator/RelationshipMessage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """VectorMessage desired
VectorMessage actual
int32 id
================================================================================
MSG: Simulator/VectorMessage
float64 x
float64 y
"""
  __slots__ = ['desired','actual','id']
  _slot_types = ['Simulator/VectorMessage','Simulator/VectorMessage','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       desired,actual,id
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(RelationshipMessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.desired is None:
        self.desired = Simulator.msg.VectorMessage()
      if self.actual is None:
        self.actual = Simulator.msg.VectorMessage()
      if self.id is None:
        self.id = 0
    else:
      self.desired = Simulator.msg.VectorMessage()
      self.actual = Simulator.msg.VectorMessage()
      self.id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_4di.pack(_x.desired.x, _x.desired.y, _x.actual.x, _x.actual.y, _x.id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.desired is None:
        self.desired = Simulator.msg.VectorMessage()
      if self.actual is None:
        self.actual = Simulator.msg.VectorMessage()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.desired.x, _x.desired.y, _x.actual.x, _x.actual.y, _x.id,) = _struct_4di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_4di.pack(_x.desired.x, _x.desired.y, _x.actual.x, _x.actual.y, _x.id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.desired is None:
        self.desired = Simulator.msg.VectorMessage()
      if self.actual is None:
        self.actual = Simulator.msg.VectorMessage()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.desired.x, _x.desired.y, _x.actual.x, _x.actual.y, _x.id,) = _struct_4di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_4di = struct.Struct("<4di")
