"""autogenerated by genmsg_py from StateMessage.msg. Do not edit."""
import roslib.message
import struct

import Simulator.msg

class StateMessage(roslib.message.Message):
  _md5sum = "5719d4b054f34dae3ad68ebff33db700"
  _type = "Simulator/StateMessage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """FormationMessage formation
VectorMessage frp
RelationshipMessage[] relationships
VectorMessage linear_error
float64 angular_error
int32 timestep
int32 reference_id
float64 temperature
float64 heat
================================================================================
MSG: Simulator/FormationMessage
float64 radius
float64 heading
VectorMessage  seed_frp
int32   seed_id
int32   formation_id
================================================================================
MSG: Simulator/VectorMessage
float64 x
float64 y
================================================================================
MSG: Simulator/RelationshipMessage
#VectorMessage desired
#VectorMessage actual
int32 id
"""
  __slots__ = ['formation','frp','relationships','linear_error','angular_error','timestep','reference_id','temperature','heat']
  _slot_types = ['Simulator/FormationMessage','Simulator/VectorMessage','Simulator/RelationshipMessage[]','Simulator/VectorMessage','float64','int32','int32','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       formation,frp,relationships,linear_error,angular_error,timestep,reference_id,temperature,heat
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(StateMessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.formation is None:
        self.formation = Simulator.msg.FormationMessage()
      if self.frp is None:
        self.frp = Simulator.msg.VectorMessage()
      if self.relationships is None:
        self.relationships = []
      if self.linear_error is None:
        self.linear_error = Simulator.msg.VectorMessage()
      if self.angular_error is None:
        self.angular_error = 0.
      if self.timestep is None:
        self.timestep = 0
      if self.reference_id is None:
        self.reference_id = 0
      if self.temperature is None:
        self.temperature = 0.
      if self.heat is None:
        self.heat = 0.
    else:
      self.formation = Simulator.msg.FormationMessage()
      self.frp = Simulator.msg.VectorMessage()
      self.relationships = []
      self.linear_error = Simulator.msg.VectorMessage()
      self.angular_error = 0.
      self.timestep = 0
      self.reference_id = 0
      self.temperature = 0.
      self.heat = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_4d2i2d.pack(_x.formation.radius, _x.formation.heading, _x.formation.seed_frp.x, _x.formation.seed_frp.y, _x.formation.seed_id, _x.formation.formation_id, _x.frp.x, _x.frp.y))
      length = len(self.relationships)
      buff.write(_struct_I.pack(length))
      for val1 in self.relationships:
        buff.write(_struct_i.pack(val1.id))
      _x = self
      buff.write(_struct_3d2i2d.pack(_x.linear_error.x, _x.linear_error.y, _x.angular_error, _x.timestep, _x.reference_id, _x.temperature, _x.heat))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.formation is None:
        self.formation = Simulator.msg.FormationMessage()
      if self.frp is None:
        self.frp = Simulator.msg.VectorMessage()
      if self.linear_error is None:
        self.linear_error = Simulator.msg.VectorMessage()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.formation.radius, _x.formation.heading, _x.formation.seed_frp.x, _x.formation.seed_frp.y, _x.formation.seed_id, _x.formation.formation_id, _x.frp.x, _x.frp.y,) = _struct_4d2i2d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.relationships = []
      for i in range(0, length):
        val1 = Simulator.msg.RelationshipMessage()
        start = end
        end += 4
        (val1.id,) = _struct_i.unpack(str[start:end])
        self.relationships.append(val1)
      _x = self
      start = end
      end += 48
      (_x.linear_error.x, _x.linear_error.y, _x.angular_error, _x.timestep, _x.reference_id, _x.temperature, _x.heat,) = _struct_3d2i2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_4d2i2d.pack(_x.formation.radius, _x.formation.heading, _x.formation.seed_frp.x, _x.formation.seed_frp.y, _x.formation.seed_id, _x.formation.formation_id, _x.frp.x, _x.frp.y))
      length = len(self.relationships)
      buff.write(_struct_I.pack(length))
      for val1 in self.relationships:
        buff.write(_struct_i.pack(val1.id))
      _x = self
      buff.write(_struct_3d2i2d.pack(_x.linear_error.x, _x.linear_error.y, _x.angular_error, _x.timestep, _x.reference_id, _x.temperature, _x.heat))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.formation is None:
        self.formation = Simulator.msg.FormationMessage()
      if self.frp is None:
        self.frp = Simulator.msg.VectorMessage()
      if self.linear_error is None:
        self.linear_error = Simulator.msg.VectorMessage()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.formation.radius, _x.formation.heading, _x.formation.seed_frp.x, _x.formation.seed_frp.y, _x.formation.seed_id, _x.formation.formation_id, _x.frp.x, _x.frp.y,) = _struct_4d2i2d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.relationships = []
      for i in range(0, length):
        val1 = Simulator.msg.RelationshipMessage()
        start = end
        end += 4
        (val1.id,) = _struct_i.unpack(str[start:end])
        self.relationships.append(val1)
      _x = self
      start = end
      end += 48
      (_x.linear_error.x, _x.linear_error.y, _x.angular_error, _x.timestep, _x.reference_id, _x.temperature, _x.heat,) = _struct_3d2i2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_i = struct.Struct("<i")
_struct_3d2i2d = struct.Struct("<3d2i2d")
_struct_4d2i2d = struct.Struct("<4d2i2d")
