(cl:defpackage Simulator-srv
  (:use )
  (:export
   "CURRENTFORMATION"
   "<CURRENTFORMATION-REQUEST>"
   "CURRENTFORMATION-REQUEST"
   "<CURRENTFORMATION-RESPONSE>"
   "CURRENTFORMATION-RESPONSE"
   "STATE"
   "<STATE-REQUEST>"
   "STATE-REQUEST"
   "<STATE-RESPONSE>"
   "STATE-RESPONSE"
  ))

